name: pbdl
description: A starting point for Dart libraries or applications.
version: 2.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.9.0
  hex: ^0.2.0
  quick_log: ^5.5.0
  http2: ^2.3.0
  path: ^1.8.0
  azblob: ^2.0.0
  recase: ^4.1.0
  archive: ^3.1.2
  meta: ^1.16.0
  uuid: ^4.5.1
  get_it: ^8.0.2

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  pedantic: ^1.10.0
  test: ^1.16.0
